### ISSUE TITLE
Create a GitHub Actions Workflow to Test GCP Permissions for the Terraform Agent

### ISSUE THREAD

**Issue by jaylong255** [Cyberworld-builders/gcp-iac#3]

**Comment by jaylong255** [comment]
```yaml
name: Terraform Plan on GCP with Service Account Key

on:
  pull_request:
    paths:
      - 'terraform/**'
      - './github/workflows/**'
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_PROJECT_NUMBER: ${{ secrets.GCP_PROJECT_NUMBER }}
  TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
    - id: 'auth'
      name: Authenticate with GCP
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
        service_account: 'tf-managed-resources@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Terraform Init
      working-directory: terraform/tf-managed-resources
      run: terraform init -input=false
      env:
        GOOGLE_CREDENTIALS: ${{ steps.auth.outputs.credentials_json }}

    
    - name: Terraform Plan
      working-directory: terraform/tf-managed-resources
      run: terraform plan -input=false -out=tfplan -no-color
      env:
        GOOGLE_CREDENTIALS: ${{ steps.auth.outputs.credentials_json }}

```
